language: python
python:
  '3.6'
install:
  pip install tox-travis coverage codecov
script:
  python setup.py test
script:
  tox
script:
  coverage run --source=ipy_converter -m unittest discover -s tests/
after_success:
  codecov
